//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonsName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonsName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorUI.ButtonsName", typeof(ButtonsName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string CLEAR_KEY {
            get {
                return ResourceManager.GetString("CLEAR_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string COPY_MENU_ITEM {
            get {
                return ResourceManager.GetString("COPY_MENU_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string DELETE_KEY {
            get {
                return ResourceManager.GetString("DELETE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT_MENU {
            get {
                return ResourceManager.GetString("EDIT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EQUALS_KEY {
            get {
                return ResourceManager.GetString("EQUALS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT_MENU {
            get {
                return ResourceManager.GetString("EXIT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP_MENU {
            get {
                return ResourceManager.GetString("HELP_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M+.
        /// </summary>
        internal static string MEMORY_ADD {
            get {
                return ResourceManager.GetString("MEMORY_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MC.
        /// </summary>
        internal static string MEMORY_CLEAR {
            get {
                return ResourceManager.GetString("MEMORY_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is stored in memory.
        /// </summary>
        internal static string MEMORY_MESSAGE {
            get {
                return ResourceManager.GetString("MEMORY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS.
        /// </summary>
        internal static string MEMORY_STORE {
            get {
                return ResourceManager.GetString("MEMORY_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M-.
        /// </summary>
        internal static string MEMORY_SUBTRACTION {
            get {
                return ResourceManager.GetString("MEMORY_SUBTRACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PASTE_MENU_ITEM {
            get {
                return ResourceManager.GetString("PASTE_MENU_ITEM", resourceCulture);
            }
        }
    }
}
