//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorLibrary.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or delete this operator.
        /// </summary>
        internal static string ADD_DELETE_OPERATOR {
            get {
                return ResourceManager.GetString("ADD_DELETE_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by Zero..
        /// </summary>
        internal static string CANNOT_DIVIDE_ZERO {
            get {
                return ResourceManager.GetString("CANNOT_DIVIDE_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brackets are not inserted properly. Please check!.
        /// </summary>
        internal static string INVALID_OPERATION_BRACKETS {
            get {
                return ResourceManager.GetString("INVALID_OPERATION_BRACKETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing To Evaluate.
        /// </summary>
        internal static string INVALID_OPERATION_EMPTY {
            get {
                return ResourceManager.GetString("INVALID_OPERATION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your expression! There is some error evaluating it..
        /// </summary>
        internal static string INVALID_OPERATION_GENERAL {
            get {
                return ResourceManager.GetString("INVALID_OPERATION_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Not Found.
        /// </summary>
        internal static string KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are less number of operands available for operator : .
        /// </summary>
        internal static string LESS_OPERANDS {
            get {
                return ResourceManager.GetString("LESS_OPERANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some extra operands. Please check your expression .
        /// </summary>
        internal static string MORE_OPERANDS {
            get {
                return ResourceManager.GetString("MORE_OPERANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of the result is overflowed. Please try with smaller inputs.
        /// </summary>
        internal static string RANGE_OVERFLOW {
            get {
                return ResourceManager.GetString("RANGE_OVERFLOW", resourceCulture);
            }
        }
    }
}
